# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ArtistProfileUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, stage_name: str=None, bio: str=None, avatar_url: str=None, banner_url: str=None, socials: Dict[str, str]=None):  # noqa: E501
        """ArtistProfileUpdate - a model defined in Swagger

        :param stage_name: The stage_name of this ArtistProfileUpdate.  # noqa: E501
        :type stage_name: str
        :param bio: The bio of this ArtistProfileUpdate.  # noqa: E501
        :type bio: str
        :param avatar_url: The avatar_url of this ArtistProfileUpdate.  # noqa: E501
        :type avatar_url: str
        :param banner_url: The banner_url of this ArtistProfileUpdate.  # noqa: E501
        :type banner_url: str
        :param socials: The socials of this ArtistProfileUpdate.  # noqa: E501
        :type socials: Dict[str, str]
        """
        self.swagger_types = {
            'stage_name': str,
            'bio': str,
            'avatar_url': str,
            'banner_url': str,
            'socials': Dict[str, str]
        }

        self.attribute_map = {
            'stage_name': 'stageName',
            'bio': 'bio',
            'avatar_url': 'avatarUrl',
            'banner_url': 'bannerUrl',
            'socials': 'socials'
        }
        self._stage_name = stage_name
        self._bio = bio
        self._avatar_url = avatar_url
        self._banner_url = banner_url
        self._socials = socials

    @classmethod
    def from_dict(cls, dikt) -> 'ArtistProfileUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ArtistProfileUpdate of this ArtistProfileUpdate.  # noqa: E501
        :rtype: ArtistProfileUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stage_name(self) -> str:
        """Gets the stage_name of this ArtistProfileUpdate.


        :return: The stage_name of this ArtistProfileUpdate.
        :rtype: str
        """
        return self._stage_name

    @stage_name.setter
    def stage_name(self, stage_name: str):
        """Sets the stage_name of this ArtistProfileUpdate.


        :param stage_name: The stage_name of this ArtistProfileUpdate.
        :type stage_name: str
        """

        self._stage_name = stage_name

    @property
    def bio(self) -> str:
        """Gets the bio of this ArtistProfileUpdate.


        :return: The bio of this ArtistProfileUpdate.
        :rtype: str
        """
        return self._bio

    @bio.setter
    def bio(self, bio: str):
        """Sets the bio of this ArtistProfileUpdate.


        :param bio: The bio of this ArtistProfileUpdate.
        :type bio: str
        """

        self._bio = bio

    @property
    def avatar_url(self) -> str:
        """Gets the avatar_url of this ArtistProfileUpdate.


        :return: The avatar_url of this ArtistProfileUpdate.
        :rtype: str
        """
        return self._avatar_url

    @avatar_url.setter
    def avatar_url(self, avatar_url: str):
        """Sets the avatar_url of this ArtistProfileUpdate.


        :param avatar_url: The avatar_url of this ArtistProfileUpdate.
        :type avatar_url: str
        """

        self._avatar_url = avatar_url

    @property
    def banner_url(self) -> str:
        """Gets the banner_url of this ArtistProfileUpdate.


        :return: The banner_url of this ArtistProfileUpdate.
        :rtype: str
        """
        return self._banner_url

    @banner_url.setter
    def banner_url(self, banner_url: str):
        """Sets the banner_url of this ArtistProfileUpdate.


        :param banner_url: The banner_url of this ArtistProfileUpdate.
        :type banner_url: str
        """

        self._banner_url = banner_url

    @property
    def socials(self) -> Dict[str, str]:
        """Gets the socials of this ArtistProfileUpdate.


        :return: The socials of this ArtistProfileUpdate.
        :rtype: Dict[str, str]
        """
        return self._socials

    @socials.setter
    def socials(self, socials: Dict[str, str]):
        """Sets the socials of this ArtistProfileUpdate.


        :param socials: The socials of this ArtistProfileUpdate.
        :type socials: Dict[str, str]
        """

        self._socials = socials
