# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ArtistProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, stage_name: str=None, bio: str=None, avatar_url: str=None, banner_url: str=None, socials: Dict[str, str]=None, verified: bool=None, created_at: datetime=None, updated_at: datetime=None):  # noqa: E501
        """ArtistProfile - a model defined in Swagger

        :param id: The id of this ArtistProfile.  # noqa: E501
        :type id: str
        :param stage_name: The stage_name of this ArtistProfile.  # noqa: E501
        :type stage_name: str
        :param bio: The bio of this ArtistProfile.  # noqa: E501
        :type bio: str
        :param avatar_url: The avatar_url of this ArtistProfile.  # noqa: E501
        :type avatar_url: str
        :param banner_url: The banner_url of this ArtistProfile.  # noqa: E501
        :type banner_url: str
        :param socials: The socials of this ArtistProfile.  # noqa: E501
        :type socials: Dict[str, str]
        :param verified: The verified of this ArtistProfile.  # noqa: E501
        :type verified: bool
        :param created_at: The created_at of this ArtistProfile.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this ArtistProfile.  # noqa: E501
        :type updated_at: datetime
        """
        self.swagger_types = {
            'id': str,
            'stage_name': str,
            'bio': str,
            'avatar_url': str,
            'banner_url': str,
            'socials': Dict[str, str],
            'verified': bool,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'stage_name': 'stageName',
            'bio': 'bio',
            'avatar_url': 'avatarUrl',
            'banner_url': 'bannerUrl',
            'socials': 'socials',
            'verified': 'verified',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }
        self._id = id
        self._stage_name = stage_name
        self._bio = bio
        self._avatar_url = avatar_url
        self._banner_url = banner_url
        self._socials = socials
        self._verified = verified
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'ArtistProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ArtistProfile of this ArtistProfile.  # noqa: E501
        :rtype: ArtistProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ArtistProfile.


        :return: The id of this ArtistProfile.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ArtistProfile.


        :param id: The id of this ArtistProfile.
        :type id: str
        """

        self._id = id

    @property
    def stage_name(self) -> str:
        """Gets the stage_name of this ArtistProfile.


        :return: The stage_name of this ArtistProfile.
        :rtype: str
        """
        return self._stage_name

    @stage_name.setter
    def stage_name(self, stage_name: str):
        """Sets the stage_name of this ArtistProfile.


        :param stage_name: The stage_name of this ArtistProfile.
        :type stage_name: str
        """

        self._stage_name = stage_name

    @property
    def bio(self) -> str:
        """Gets the bio of this ArtistProfile.


        :return: The bio of this ArtistProfile.
        :rtype: str
        """
        return self._bio

    @bio.setter
    def bio(self, bio: str):
        """Sets the bio of this ArtistProfile.


        :param bio: The bio of this ArtistProfile.
        :type bio: str
        """

        self._bio = bio

    @property
    def avatar_url(self) -> str:
        """Gets the avatar_url of this ArtistProfile.


        :return: The avatar_url of this ArtistProfile.
        :rtype: str
        """
        return self._avatar_url

    @avatar_url.setter
    def avatar_url(self, avatar_url: str):
        """Sets the avatar_url of this ArtistProfile.


        :param avatar_url: The avatar_url of this ArtistProfile.
        :type avatar_url: str
        """

        self._avatar_url = avatar_url

    @property
    def banner_url(self) -> str:
        """Gets the banner_url of this ArtistProfile.


        :return: The banner_url of this ArtistProfile.
        :rtype: str
        """
        return self._banner_url

    @banner_url.setter
    def banner_url(self, banner_url: str):
        """Sets the banner_url of this ArtistProfile.


        :param banner_url: The banner_url of this ArtistProfile.
        :type banner_url: str
        """

        self._banner_url = banner_url

    @property
    def socials(self) -> Dict[str, str]:
        """Gets the socials of this ArtistProfile.


        :return: The socials of this ArtistProfile.
        :rtype: Dict[str, str]
        """
        return self._socials

    @socials.setter
    def socials(self, socials: Dict[str, str]):
        """Sets the socials of this ArtistProfile.


        :param socials: The socials of this ArtistProfile.
        :type socials: Dict[str, str]
        """

        self._socials = socials

    @property
    def verified(self) -> bool:
        """Gets the verified of this ArtistProfile.


        :return: The verified of this ArtistProfile.
        :rtype: bool
        """
        return self._verified

    @verified.setter
    def verified(self, verified: bool):
        """Sets the verified of this ArtistProfile.


        :param verified: The verified of this ArtistProfile.
        :type verified: bool
        """

        self._verified = verified

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this ArtistProfile.


        :return: The created_at of this ArtistProfile.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this ArtistProfile.


        :param created_at: The created_at of this ArtistProfile.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this ArtistProfile.


        :return: The updated_at of this ArtistProfile.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this ArtistProfile.


        :param updated_at: The updated_at of this ArtistProfile.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
