# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.token_pair import TokenPair  # noqa: F401,E501
from swagger_server.models.user_private import UserPrivate  # noqa: F401,E501
from swagger_server import util


class AuthResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user: UserPrivate=None, tokens: TokenPair=None):  # noqa: E501
        """AuthResponse - a model defined in Swagger

        :param user: The user of this AuthResponse.  # noqa: E501
        :type user: UserPrivate
        :param tokens: The tokens of this AuthResponse.  # noqa: E501
        :type tokens: TokenPair
        """
        self.swagger_types = {
            'user': UserPrivate,
            'tokens': TokenPair
        }

        self.attribute_map = {
            'user': 'user',
            'tokens': 'tokens'
        }
        self._user = user
        self._tokens = tokens

    @classmethod
    def from_dict(cls, dikt) -> 'AuthResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthResponse of this AuthResponse.  # noqa: E501
        :rtype: AuthResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> UserPrivate:
        """Gets the user of this AuthResponse.


        :return: The user of this AuthResponse.
        :rtype: UserPrivate
        """
        return self._user

    @user.setter
    def user(self, user: UserPrivate):
        """Sets the user of this AuthResponse.


        :param user: The user of this AuthResponse.
        :type user: UserPrivate
        """

        self._user = user

    @property
    def tokens(self) -> TokenPair:
        """Gets the tokens of this AuthResponse.


        :return: The tokens of this AuthResponse.
        :rtype: TokenPair
        """
        return self._tokens

    @tokens.setter
    def tokens(self, tokens: TokenPair):
        """Sets the tokens of this AuthResponse.


        :param tokens: The tokens of this AuthResponse.
        :type tokens: TokenPair
        """

        self._tokens = tokens
