# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.consents import Consents  # noqa: F401,E501
from swagger_server import util


class ConsentsUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, email_marketing: bool=None, personalized_recommendations: bool=None, data_processing_accepted: bool=None):  # noqa: E501
        """ConsentsUpdate - a model defined in Swagger

        :param email_marketing: The email_marketing of this ConsentsUpdate.  # noqa: E501
        :type email_marketing: bool
        :param personalized_recommendations: The personalized_recommendations of this ConsentsUpdate.  # noqa: E501
        :type personalized_recommendations: bool
        :param data_processing_accepted: The data_processing_accepted of this ConsentsUpdate.  # noqa: E501
        :type data_processing_accepted: bool
        """
        self.swagger_types = {
            'email_marketing': bool,
            'personalized_recommendations': bool,
            'data_processing_accepted': bool
        }

        self.attribute_map = {
            'email_marketing': 'emailMarketing',
            'personalized_recommendations': 'personalizedRecommendations',
            'data_processing_accepted': 'dataProcessingAccepted'
        }
        self._email_marketing = email_marketing
        self._personalized_recommendations = personalized_recommendations
        self._data_processing_accepted = data_processing_accepted

    @classmethod
    def from_dict(cls, dikt) -> 'ConsentsUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConsentsUpdate of this ConsentsUpdate.  # noqa: E501
        :rtype: ConsentsUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email_marketing(self) -> bool:
        """Gets the email_marketing of this ConsentsUpdate.


        :return: The email_marketing of this ConsentsUpdate.
        :rtype: bool
        """
        return self._email_marketing

    @email_marketing.setter
    def email_marketing(self, email_marketing: bool):
        """Sets the email_marketing of this ConsentsUpdate.


        :param email_marketing: The email_marketing of this ConsentsUpdate.
        :type email_marketing: bool
        """

        self._email_marketing = email_marketing

    @property
    def personalized_recommendations(self) -> bool:
        """Gets the personalized_recommendations of this ConsentsUpdate.


        :return: The personalized_recommendations of this ConsentsUpdate.
        :rtype: bool
        """
        return self._personalized_recommendations

    @personalized_recommendations.setter
    def personalized_recommendations(self, personalized_recommendations: bool):
        """Sets the personalized_recommendations of this ConsentsUpdate.


        :param personalized_recommendations: The personalized_recommendations of this ConsentsUpdate.
        :type personalized_recommendations: bool
        """

        self._personalized_recommendations = personalized_recommendations

    @property
    def data_processing_accepted(self) -> bool:
        """Gets the data_processing_accepted of this ConsentsUpdate.


        :return: The data_processing_accepted of this ConsentsUpdate.
        :rtype: bool
        """
        return self._data_processing_accepted

    @data_processing_accepted.setter
    def data_processing_accepted(self, data_processing_accepted: bool):
        """Sets the data_processing_accepted of this ConsentsUpdate.


        :param data_processing_accepted: The data_processing_accepted of this ConsentsUpdate.
        :type data_processing_accepted: bool
        """

        self._data_processing_accepted = data_processing_accepted
