# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LoginRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, email_or_username: str=None, password: str=None, mfa_code: str=None):  # noqa: E501
        """LoginRequest - a model defined in Swagger

        :param email_or_username: The email_or_username of this LoginRequest.  # noqa: E501
        :type email_or_username: str
        :param password: The password of this LoginRequest.  # noqa: E501
        :type password: str
        :param mfa_code: The mfa_code of this LoginRequest.  # noqa: E501
        :type mfa_code: str
        """
        self.swagger_types = {
            'email_or_username': str,
            'password': str,
            'mfa_code': str
        }

        self.attribute_map = {
            'email_or_username': 'emailOrUsername',
            'password': 'password',
            'mfa_code': 'mfaCode'
        }
        self._email_or_username = email_or_username
        self._password = password
        self._mfa_code = mfa_code

    @classmethod
    def from_dict(cls, dikt) -> 'LoginRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginRequest of this LoginRequest.  # noqa: E501
        :rtype: LoginRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email_or_username(self) -> str:
        """Gets the email_or_username of this LoginRequest.


        :return: The email_or_username of this LoginRequest.
        :rtype: str
        """
        return self._email_or_username

    @email_or_username.setter
    def email_or_username(self, email_or_username: str):
        """Sets the email_or_username of this LoginRequest.


        :param email_or_username: The email_or_username of this LoginRequest.
        :type email_or_username: str
        """
        if email_or_username is None:
            raise ValueError("Invalid value for `email_or_username`, must not be `None`")  # noqa: E501

        self._email_or_username = email_or_username

    @property
    def password(self) -> str:
        """Gets the password of this LoginRequest.


        :return: The password of this LoginRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this LoginRequest.


        :param password: The password of this LoginRequest.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def mfa_code(self) -> str:
        """Gets the mfa_code of this LoginRequest.

        Código TOTP si MFA está activado  # noqa: E501

        :return: The mfa_code of this LoginRequest.
        :rtype: str
        """
        return self._mfa_code

    @mfa_code.setter
    def mfa_code(self, mfa_code: str):
        """Sets the mfa_code of this LoginRequest.

        Código TOTP si MFA está activado  # noqa: E501

        :param mfa_code: The mfa_code of this LoginRequest.
        :type mfa_code: str
        """

        self._mfa_code = mfa_code
