# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MeFollowsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: str=None):  # noqa: E501
        """MeFollowsBody - a model defined in Swagger

        :param user_id: The user_id of this MeFollowsBody.  # noqa: E501
        :type user_id: str
        """
        self.swagger_types = {
            'user_id': str
        }

        self.attribute_map = {
            'user_id': 'userId'
        }
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'MeFollowsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The me_follows_body of this MeFollowsBody.  # noqa: E501
        :rtype: MeFollowsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this MeFollowsBody.


        :return: The user_id of this MeFollowsBody.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this MeFollowsBody.


        :param user_id: The user_id of this MeFollowsBody.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id
