# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MePasswordBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, current_password: str=None, new_password: str=None):  # noqa: E501
        """MePasswordBody - a model defined in Swagger

        :param current_password: The current_password of this MePasswordBody.  # noqa: E501
        :type current_password: str
        :param new_password: The new_password of this MePasswordBody.  # noqa: E501
        :type new_password: str
        """
        self.swagger_types = {
            'current_password': str,
            'new_password': str
        }

        self.attribute_map = {
            'current_password': 'currentPassword',
            'new_password': 'newPassword'
        }
        self._current_password = current_password
        self._new_password = new_password

    @classmethod
    def from_dict(cls, dikt) -> 'MePasswordBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The me_password_body of this MePasswordBody.  # noqa: E501
        :rtype: MePasswordBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_password(self) -> str:
        """Gets the current_password of this MePasswordBody.


        :return: The current_password of this MePasswordBody.
        :rtype: str
        """
        return self._current_password

    @current_password.setter
    def current_password(self, current_password: str):
        """Sets the current_password of this MePasswordBody.


        :param current_password: The current_password of this MePasswordBody.
        :type current_password: str
        """
        if current_password is None:
            raise ValueError("Invalid value for `current_password`, must not be `None`")  # noqa: E501

        self._current_password = current_password

    @property
    def new_password(self) -> str:
        """Gets the new_password of this MePasswordBody.


        :return: The new_password of this MePasswordBody.
        :rtype: str
        """
        return self._new_password

    @new_password.setter
    def new_password(self, new_password: str):
        """Sets the new_password of this MePasswordBody.


        :param new_password: The new_password of this MePasswordBody.
        :type new_password: str
        """
        if new_password is None:
            raise ValueError("Invalid value for `new_password`, must not be `None`")  # noqa: E501

        self._new_password = new_password
