# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user_public import UserPublic  # noqa: F401,E501
from swagger_server import util


class PagedUsers(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, items: List[UserPublic]=None, page: int=None, page_size: int=None, total: int=None):  # noqa: E501
        """PagedUsers - a model defined in Swagger

        :param items: The items of this PagedUsers.  # noqa: E501
        :type items: List[UserPublic]
        :param page: The page of this PagedUsers.  # noqa: E501
        :type page: int
        :param page_size: The page_size of this PagedUsers.  # noqa: E501
        :type page_size: int
        :param total: The total of this PagedUsers.  # noqa: E501
        :type total: int
        """
        self.swagger_types = {
            'items': List[UserPublic],
            'page': int,
            'page_size': int,
            'total': int
        }

        self.attribute_map = {
            'items': 'items',
            'page': 'page',
            'page_size': 'pageSize',
            'total': 'total'
        }
        self._items = items
        self._page = page
        self._page_size = page_size
        self._total = total

    @classmethod
    def from_dict(cls, dikt) -> 'PagedUsers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PagedUsers of this PagedUsers.  # noqa: E501
        :rtype: PagedUsers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[UserPublic]:
        """Gets the items of this PagedUsers.


        :return: The items of this PagedUsers.
        :rtype: List[UserPublic]
        """
        return self._items

    @items.setter
    def items(self, items: List[UserPublic]):
        """Sets the items of this PagedUsers.


        :param items: The items of this PagedUsers.
        :type items: List[UserPublic]
        """

        self._items = items

    @property
    def page(self) -> int:
        """Gets the page of this PagedUsers.


        :return: The page of this PagedUsers.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this PagedUsers.


        :param page: The page of this PagedUsers.
        :type page: int
        """

        self._page = page

    @property
    def page_size(self) -> int:
        """Gets the page_size of this PagedUsers.


        :return: The page_size of this PagedUsers.
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size: int):
        """Sets the page_size of this PagedUsers.


        :param page_size: The page_size of this PagedUsers.
        :type page_size: int
        """

        self._page_size = page_size

    @property
    def total(self) -> int:
        """Gets the total of this PagedUsers.


        :return: The total of this PagedUsers.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this PagedUsers.


        :param total: The total of this PagedUsers.
        :type total: int
        """

        self._total = total
