# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.playlist_visibility import PlaylistVisibility  # noqa: F401,E501
from swagger_server import util


class PlaylistShare(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, visibility: PlaylistVisibility=None):  # noqa: E501
        """PlaylistShare - a model defined in Swagger

        :param visibility: The visibility of this PlaylistShare.  # noqa: E501
        :type visibility: PlaylistVisibility
        """
        self.swagger_types = {
            'visibility': PlaylistVisibility
        }

        self.attribute_map = {
            'visibility': 'visibility'
        }
        self._visibility = visibility

    @classmethod
    def from_dict(cls, dikt) -> 'PlaylistShare':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlaylistShare of this PlaylistShare.  # noqa: E501
        :rtype: PlaylistShare
        """
        return util.deserialize_model(dikt, cls)

    @property
    def visibility(self) -> PlaylistVisibility:
        """Gets the visibility of this PlaylistShare.


        :return: The visibility of this PlaylistShare.
        :rtype: PlaylistVisibility
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility: PlaylistVisibility):
        """Sets the visibility of this PlaylistShare.


        :param visibility: The visibility of this PlaylistShare.
        :type visibility: PlaylistVisibility
        """

        self._visibility = visibility
