# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PlaylistItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, track_id: str=None, position: int=None, added_at: datetime=None):  # noqa: E501
        """PlaylistItem - a model defined in Swagger

        :param id: The id of this PlaylistItem.  # noqa: E501
        :type id: str
        :param track_id: The track_id of this PlaylistItem.  # noqa: E501
        :type track_id: str
        :param position: The position of this PlaylistItem.  # noqa: E501
        :type position: int
        :param added_at: The added_at of this PlaylistItem.  # noqa: E501
        :type added_at: datetime
        """
        self.swagger_types = {
            'id': str,
            'track_id': str,
            'position': int,
            'added_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'track_id': 'trackId',
            'position': 'position',
            'added_at': 'addedAt'
        }
        self._id = id
        self._track_id = track_id
        self._position = position
        self._added_at = added_at

    @classmethod
    def from_dict(cls, dikt) -> 'PlaylistItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlaylistItem of this PlaylistItem.  # noqa: E501
        :rtype: PlaylistItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this PlaylistItem.


        :return: The id of this PlaylistItem.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this PlaylistItem.


        :param id: The id of this PlaylistItem.
        :type id: str
        """

        self._id = id

    @property
    def track_id(self) -> str:
        """Gets the track_id of this PlaylistItem.


        :return: The track_id of this PlaylistItem.
        :rtype: str
        """
        return self._track_id

    @track_id.setter
    def track_id(self, track_id: str):
        """Sets the track_id of this PlaylistItem.


        :param track_id: The track_id of this PlaylistItem.
        :type track_id: str
        """

        self._track_id = track_id

    @property
    def position(self) -> int:
        """Gets the position of this PlaylistItem.


        :return: The position of this PlaylistItem.
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position: int):
        """Sets the position of this PlaylistItem.


        :param position: The position of this PlaylistItem.
        :type position: int
        """

        self._position = position

    @property
    def added_at(self) -> datetime:
        """Gets the added_at of this PlaylistItem.


        :return: The added_at of this PlaylistItem.
        :rtype: datetime
        """
        return self._added_at

    @added_at.setter
    def added_at(self, added_at: datetime):
        """Sets the added_at of this PlaylistItem.


        :param added_at: The added_at of this PlaylistItem.
        :type added_at: datetime
        """

        self._added_at = added_at
