# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.playlist_item import PlaylistItem  # noqa: F401,E501
from swagger_server.models.playlist_visibility import PlaylistVisibility  # noqa: F401,E501
from swagger_server import util


class Playlist(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, owner_id: str=None, title: str=None, description: str=None, visibility: PlaylistVisibility=None, share_url: str=None, created_at: datetime=None, updated_at: datetime=None, items: List[PlaylistItem]=None):  # noqa: E501
        """Playlist - a model defined in Swagger

        :param id: The id of this Playlist.  # noqa: E501
        :type id: str
        :param owner_id: The owner_id of this Playlist.  # noqa: E501
        :type owner_id: str
        :param title: The title of this Playlist.  # noqa: E501
        :type title: str
        :param description: The description of this Playlist.  # noqa: E501
        :type description: str
        :param visibility: The visibility of this Playlist.  # noqa: E501
        :type visibility: PlaylistVisibility
        :param share_url: The share_url of this Playlist.  # noqa: E501
        :type share_url: str
        :param created_at: The created_at of this Playlist.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Playlist.  # noqa: E501
        :type updated_at: datetime
        :param items: The items of this Playlist.  # noqa: E501
        :type items: List[PlaylistItem]
        """
        self.swagger_types = {
            'id': str,
            'owner_id': str,
            'title': str,
            'description': str,
            'visibility': PlaylistVisibility,
            'share_url': str,
            'created_at': datetime,
            'updated_at': datetime,
            'items': List[PlaylistItem]
        }

        self.attribute_map = {
            'id': 'id',
            'owner_id': 'ownerId',
            'title': 'title',
            'description': 'description',
            'visibility': 'visibility',
            'share_url': 'shareUrl',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt',
            'items': 'items'
        }
        self._id = id
        self._owner_id = owner_id
        self._title = title
        self._description = description
        self._visibility = visibility
        self._share_url = share_url
        self._created_at = created_at
        self._updated_at = updated_at
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'Playlist':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Playlist of this Playlist.  # noqa: E501
        :rtype: Playlist
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Playlist.


        :return: The id of this Playlist.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Playlist.


        :param id: The id of this Playlist.
        :type id: str
        """

        self._id = id

    @property
    def owner_id(self) -> str:
        """Gets the owner_id of this Playlist.


        :return: The owner_id of this Playlist.
        :rtype: str
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id: str):
        """Sets the owner_id of this Playlist.


        :param owner_id: The owner_id of this Playlist.
        :type owner_id: str
        """

        self._owner_id = owner_id

    @property
    def title(self) -> str:
        """Gets the title of this Playlist.


        :return: The title of this Playlist.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Playlist.


        :param title: The title of this Playlist.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this Playlist.


        :return: The description of this Playlist.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Playlist.


        :param description: The description of this Playlist.
        :type description: str
        """

        self._description = description

    @property
    def visibility(self) -> PlaylistVisibility:
        """Gets the visibility of this Playlist.


        :return: The visibility of this Playlist.
        :rtype: PlaylistVisibility
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility: PlaylistVisibility):
        """Sets the visibility of this Playlist.


        :param visibility: The visibility of this Playlist.
        :type visibility: PlaylistVisibility
        """

        self._visibility = visibility

    @property
    def share_url(self) -> str:
        """Gets the share_url of this Playlist.


        :return: The share_url of this Playlist.
        :rtype: str
        """
        return self._share_url

    @share_url.setter
    def share_url(self, share_url: str):
        """Sets the share_url of this Playlist.


        :param share_url: The share_url of this Playlist.
        :type share_url: str
        """

        self._share_url = share_url

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Playlist.


        :return: The created_at of this Playlist.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Playlist.


        :param created_at: The created_at of this Playlist.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Playlist.


        :return: The updated_at of this Playlist.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Playlist.


        :param updated_at: The updated_at of this Playlist.
        :type updated_at: datetime
        """

        self._updated_at = updated_at

    @property
    def items(self) -> List[PlaylistItem]:
        """Gets the items of this Playlist.


        :return: The items of this Playlist.
        :rtype: List[PlaylistItem]
        """
        return self._items

    @items.setter
    def items(self, items: List[PlaylistItem]):
        """Sets the items of this Playlist.


        :param items: The items of this Playlist.
        :type items: List[PlaylistItem]
        """

        self._items = items
