# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PlaylistIdItemsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order: List[str]=None):  # noqa: E501
        """PlaylistIdItemsBody - a model defined in Swagger

        :param order: The order of this PlaylistIdItemsBody.  # noqa: E501
        :type order: List[str]
        """
        self.swagger_types = {
            'order': List[str]
        }

        self.attribute_map = {
            'order': 'order'
        }
        self._order = order

    @classmethod
    def from_dict(cls, dikt) -> 'PlaylistIdItemsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The playlistId_items_body of this PlaylistIdItemsBody.  # noqa: E501
        :rtype: PlaylistIdItemsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order(self) -> List[str]:
        """Gets the order of this PlaylistIdItemsBody.


        :return: The order of this PlaylistIdItemsBody.
        :rtype: List[str]
        """
        return self._order

    @order.setter
    def order(self, order: List[str]):
        """Sets the order of this PlaylistIdItemsBody.


        :param order: The order of this PlaylistIdItemsBody.
        :type order: List[str]
        """
        if order is None:
            raise ValueError("Invalid value for `order`, must not be `None`")  # noqa: E501

        self._order = order
