# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.playlist_visibility import PlaylistVisibility  # noqa: F401,E501
from swagger_server import util


class PlaylistUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, description: str=None, visibility: PlaylistVisibility=None):  # noqa: E501
        """PlaylistUpdate - a model defined in Swagger

        :param title: The title of this PlaylistUpdate.  # noqa: E501
        :type title: str
        :param description: The description of this PlaylistUpdate.  # noqa: E501
        :type description: str
        :param visibility: The visibility of this PlaylistUpdate.  # noqa: E501
        :type visibility: PlaylistVisibility
        """
        self.swagger_types = {
            'title': str,
            'description': str,
            'visibility': PlaylistVisibility
        }

        self.attribute_map = {
            'title': 'title',
            'description': 'description',
            'visibility': 'visibility'
        }
        self._title = title
        self._description = description
        self._visibility = visibility

    @classmethod
    def from_dict(cls, dikt) -> 'PlaylistUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlaylistUpdate of this PlaylistUpdate.  # noqa: E501
        :rtype: PlaylistUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this PlaylistUpdate.


        :return: The title of this PlaylistUpdate.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this PlaylistUpdate.


        :param title: The title of this PlaylistUpdate.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this PlaylistUpdate.


        :return: The description of this PlaylistUpdate.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this PlaylistUpdate.


        :param description: The description of this PlaylistUpdate.
        :type description: str
        """

        self._description = description

    @property
    def visibility(self) -> PlaylistVisibility:
        """Gets the visibility of this PlaylistUpdate.


        :return: The visibility of this PlaylistUpdate.
        :rtype: PlaylistVisibility
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility: PlaylistVisibility):
        """Sets the visibility of this PlaylistUpdate.


        :param visibility: The visibility of this PlaylistUpdate.
        :type visibility: PlaylistVisibility
        """

        self._visibility = visibility
