# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PlaylistIdItemsBody1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, track_id: str=None, position: int=None):  # noqa: E501
        """PlaylistIdItemsBody1 - a model defined in Swagger

        :param track_id: The track_id of this PlaylistIdItemsBody1.  # noqa: E501
        :type track_id: str
        :param position: The position of this PlaylistIdItemsBody1.  # noqa: E501
        :type position: int
        """
        self.swagger_types = {
            'track_id': str,
            'position': int
        }

        self.attribute_map = {
            'track_id': 'trackId',
            'position': 'position'
        }
        self._track_id = track_id
        self._position = position

    @classmethod
    def from_dict(cls, dikt) -> 'PlaylistIdItemsBody1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The playlistId_items_body_1 of this PlaylistIdItemsBody1.  # noqa: E501
        :rtype: PlaylistIdItemsBody1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def track_id(self) -> str:
        """Gets the track_id of this PlaylistIdItemsBody1.


        :return: The track_id of this PlaylistIdItemsBody1.
        :rtype: str
        """
        return self._track_id

    @track_id.setter
    def track_id(self, track_id: str):
        """Sets the track_id of this PlaylistIdItemsBody1.


        :param track_id: The track_id of this PlaylistIdItemsBody1.
        :type track_id: str
        """
        if track_id is None:
            raise ValueError("Invalid value for `track_id`, must not be `None`")  # noqa: E501

        self._track_id = track_id

    @property
    def position(self) -> int:
        """Gets the position of this PlaylistIdItemsBody1.

        Posición opcional  # noqa: E501

        :return: The position of this PlaylistIdItemsBody1.
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position: int):
        """Sets the position of this PlaylistIdItemsBody1.

        Posición opcional  # noqa: E501

        :param position: The position of this PlaylistIdItemsBody1.
        :type position: int
        """

        self._position = position
