# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.role import Role  # noqa: F401,E501
from swagger_server import util


class RegisterRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, email: str=None, password: str=None, username: str=None, role: Role=None):  # noqa: E501
        """RegisterRequest - a model defined in Swagger

        :param email: The email of this RegisterRequest.  # noqa: E501
        :type email: str
        :param password: The password of this RegisterRequest.  # noqa: E501
        :type password: str
        :param username: The username of this RegisterRequest.  # noqa: E501
        :type username: str
        :param role: The role of this RegisterRequest.  # noqa: E501
        :type role: Role
        """
        self.swagger_types = {
            'email': str,
            'password': str,
            'username': str,
            'role': Role
        }

        self.attribute_map = {
            'email': 'email',
            'password': 'password',
            'username': 'username',
            'role': 'role'
        }
        self._email = email
        self._password = password
        self._username = username
        self._role = role

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegisterRequest of this RegisterRequest.  # noqa: E501
        :rtype: RegisterRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this RegisterRequest.


        :return: The email of this RegisterRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this RegisterRequest.


        :param email: The email of this RegisterRequest.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def password(self) -> str:
        """Gets the password of this RegisterRequest.


        :return: The password of this RegisterRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this RegisterRequest.


        :param password: The password of this RegisterRequest.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def username(self) -> str:
        """Gets the username of this RegisterRequest.


        :return: The username of this RegisterRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this RegisterRequest.


        :param username: The username of this RegisterRequest.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def role(self) -> Role:
        """Gets the role of this RegisterRequest.


        :return: The role of this RegisterRequest.
        :rtype: Role
        """
        return self._role

    @role.setter
    def role(self, role: Role):
        """Sets the role of this RegisterRequest.


        :param role: The role of this RegisterRequest.
        :type role: Role
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role
