# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResetConfirmBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token: str=None, new_password: str=None):  # noqa: E501
        """ResetConfirmBody - a model defined in Swagger

        :param token: The token of this ResetConfirmBody.  # noqa: E501
        :type token: str
        :param new_password: The new_password of this ResetConfirmBody.  # noqa: E501
        :type new_password: str
        """
        self.swagger_types = {
            'token': str,
            'new_password': str
        }

        self.attribute_map = {
            'token': 'token',
            'new_password': 'newPassword'
        }
        self._token = token
        self._new_password = new_password

    @classmethod
    def from_dict(cls, dikt) -> 'ResetConfirmBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The reset_confirm_body of this ResetConfirmBody.  # noqa: E501
        :rtype: ResetConfirmBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this ResetConfirmBody.


        :return: The token of this ResetConfirmBody.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this ResetConfirmBody.


        :param token: The token of this ResetConfirmBody.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def new_password(self) -> str:
        """Gets the new_password of this ResetConfirmBody.


        :return: The new_password of this ResetConfirmBody.
        :rtype: str
        """
        return self._new_password

    @new_password.setter
    def new_password(self, new_password: str):
        """Sets the new_password of this ResetConfirmBody.


        :param new_password: The new_password of this ResetConfirmBody.
        :type new_password: str
        """
        if new_password is None:
            raise ValueError("Invalid value for `new_password`, must not be `None`")  # noqa: E501

        self._new_password = new_password
