# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReviewCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, product_id: str=None, order_id: str=None, rating: int=None, title: str=None, body: str=None):  # noqa: E501
        """ReviewCreate - a model defined in Swagger

        :param product_id: The product_id of this ReviewCreate.  # noqa: E501
        :type product_id: str
        :param order_id: The order_id of this ReviewCreate.  # noqa: E501
        :type order_id: str
        :param rating: The rating of this ReviewCreate.  # noqa: E501
        :type rating: int
        :param title: The title of this ReviewCreate.  # noqa: E501
        :type title: str
        :param body: The body of this ReviewCreate.  # noqa: E501
        :type body: str
        """
        self.swagger_types = {
            'product_id': str,
            'order_id': str,
            'rating': int,
            'title': str,
            'body': str
        }

        self.attribute_map = {
            'product_id': 'productId',
            'order_id': 'orderId',
            'rating': 'rating',
            'title': 'title',
            'body': 'body'
        }
        self._product_id = product_id
        self._order_id = order_id
        self._rating = rating
        self._title = title
        self._body = body

    @classmethod
    def from_dict(cls, dikt) -> 'ReviewCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReviewCreate of this ReviewCreate.  # noqa: E501
        :rtype: ReviewCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product_id(self) -> str:
        """Gets the product_id of this ReviewCreate.


        :return: The product_id of this ReviewCreate.
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: str):
        """Sets the product_id of this ReviewCreate.


        :param product_id: The product_id of this ReviewCreate.
        :type product_id: str
        """
        if product_id is None:
            raise ValueError("Invalid value for `product_id`, must not be `None`")  # noqa: E501

        self._product_id = product_id

    @property
    def order_id(self) -> str:
        """Gets the order_id of this ReviewCreate.


        :return: The order_id of this ReviewCreate.
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: str):
        """Sets the order_id of this ReviewCreate.


        :param order_id: The order_id of this ReviewCreate.
        :type order_id: str
        """
        if order_id is None:
            raise ValueError("Invalid value for `order_id`, must not be `None`")  # noqa: E501

        self._order_id = order_id

    @property
    def rating(self) -> int:
        """Gets the rating of this ReviewCreate.


        :return: The rating of this ReviewCreate.
        :rtype: int
        """
        return self._rating

    @rating.setter
    def rating(self, rating: int):
        """Sets the rating of this ReviewCreate.


        :param rating: The rating of this ReviewCreate.
        :type rating: int
        """
        if rating is None:
            raise ValueError("Invalid value for `rating`, must not be `None`")  # noqa: E501

        self._rating = rating

    @property
    def title(self) -> str:
        """Gets the title of this ReviewCreate.


        :return: The title of this ReviewCreate.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this ReviewCreate.


        :param title: The title of this ReviewCreate.
        :type title: str
        """

        self._title = title

    @property
    def body(self) -> str:
        """Gets the body of this ReviewCreate.


        :return: The body of this ReviewCreate.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this ReviewCreate.


        :param body: The body of this ReviewCreate.
        :type body: str
        """

        self._body = body
