# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReviewUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, rating: int=None, title: str=None, body: str=None):  # noqa: E501
        """ReviewUpdate - a model defined in Swagger

        :param rating: The rating of this ReviewUpdate.  # noqa: E501
        :type rating: int
        :param title: The title of this ReviewUpdate.  # noqa: E501
        :type title: str
        :param body: The body of this ReviewUpdate.  # noqa: E501
        :type body: str
        """
        self.swagger_types = {
            'rating': int,
            'title': str,
            'body': str
        }

        self.attribute_map = {
            'rating': 'rating',
            'title': 'title',
            'body': 'body'
        }
        self._rating = rating
        self._title = title
        self._body = body

    @classmethod
    def from_dict(cls, dikt) -> 'ReviewUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReviewUpdate of this ReviewUpdate.  # noqa: E501
        :rtype: ReviewUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rating(self) -> int:
        """Gets the rating of this ReviewUpdate.


        :return: The rating of this ReviewUpdate.
        :rtype: int
        """
        return self._rating

    @rating.setter
    def rating(self, rating: int):
        """Sets the rating of this ReviewUpdate.


        :param rating: The rating of this ReviewUpdate.
        :type rating: int
        """

        self._rating = rating

    @property
    def title(self) -> str:
        """Gets the title of this ReviewUpdate.


        :return: The title of this ReviewUpdate.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this ReviewUpdate.


        :param title: The title of this ReviewUpdate.
        :type title: str
        """

        self._title = title

    @property
    def body(self) -> str:
        """Gets the body of this ReviewUpdate.


        :return: The body of this ReviewUpdate.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this ReviewUpdate.


        :param body: The body of this ReviewUpdate.
        :type body: str
        """

        self._body = body
