# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Session(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, device: str=None, user_agent: str=None, ip: str=None, created_at: datetime=None, last_seen_at: datetime=None, current: bool=None):  # noqa: E501
        """Session - a model defined in Swagger

        :param id: The id of this Session.  # noqa: E501
        :type id: str
        :param device: The device of this Session.  # noqa: E501
        :type device: str
        :param user_agent: The user_agent of this Session.  # noqa: E501
        :type user_agent: str
        :param ip: The ip of this Session.  # noqa: E501
        :type ip: str
        :param created_at: The created_at of this Session.  # noqa: E501
        :type created_at: datetime
        :param last_seen_at: The last_seen_at of this Session.  # noqa: E501
        :type last_seen_at: datetime
        :param current: The current of this Session.  # noqa: E501
        :type current: bool
        """
        self.swagger_types = {
            'id': str,
            'device': str,
            'user_agent': str,
            'ip': str,
            'created_at': datetime,
            'last_seen_at': datetime,
            'current': bool
        }

        self.attribute_map = {
            'id': 'id',
            'device': 'device',
            'user_agent': 'userAgent',
            'ip': 'ip',
            'created_at': 'createdAt',
            'last_seen_at': 'lastSeenAt',
            'current': 'current'
        }
        self._id = id
        self._device = device
        self._user_agent = user_agent
        self._ip = ip
        self._created_at = created_at
        self._last_seen_at = last_seen_at
        self._current = current

    @classmethod
    def from_dict(cls, dikt) -> 'Session':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Session of this Session.  # noqa: E501
        :rtype: Session
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Session.


        :return: The id of this Session.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Session.


        :param id: The id of this Session.
        :type id: str
        """

        self._id = id

    @property
    def device(self) -> str:
        """Gets the device of this Session.


        :return: The device of this Session.
        :rtype: str
        """
        return self._device

    @device.setter
    def device(self, device: str):
        """Sets the device of this Session.


        :param device: The device of this Session.
        :type device: str
        """

        self._device = device

    @property
    def user_agent(self) -> str:
        """Gets the user_agent of this Session.


        :return: The user_agent of this Session.
        :rtype: str
        """
        return self._user_agent

    @user_agent.setter
    def user_agent(self, user_agent: str):
        """Sets the user_agent of this Session.


        :param user_agent: The user_agent of this Session.
        :type user_agent: str
        """

        self._user_agent = user_agent

    @property
    def ip(self) -> str:
        """Gets the ip of this Session.


        :return: The ip of this Session.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip: str):
        """Sets the ip of this Session.


        :param ip: The ip of this Session.
        :type ip: str
        """

        self._ip = ip

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Session.


        :return: The created_at of this Session.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Session.


        :param created_at: The created_at of this Session.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def last_seen_at(self) -> datetime:
        """Gets the last_seen_at of this Session.


        :return: The last_seen_at of this Session.
        :rtype: datetime
        """
        return self._last_seen_at

    @last_seen_at.setter
    def last_seen_at(self, last_seen_at: datetime):
        """Sets the last_seen_at of this Session.


        :param last_seen_at: The last_seen_at of this Session.
        :type last_seen_at: datetime
        """

        self._last_seen_at = last_seen_at

    @property
    def current(self) -> bool:
        """Gets the current of this Session.


        :return: The current of this Session.
        :rtype: bool
        """
        return self._current

    @current.setter
    def current(self, current: bool):
        """Sets the current of this Session.


        :param current: The current of this Session.
        :type current: bool
        """

        self._current = current
