# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.role import Role  # noqa: F401,E501
from swagger_server.models.user_public import UserPublic  # noqa: F401,E501
from swagger_server import util


class UserPrivate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, email: str=None, email_verified: bool=None, id: str=None, username: str=None, role: Role=None, avatar_url: str=None, bio: str=None):  # noqa: E501
        """UserPrivate - a model defined in Swagger

        :param email: The email of this UserPrivate.  # noqa: E501
        :type email: str
        :param email_verified: The email_verified of this UserPrivate.  # noqa: E501
        :type email_verified: bool
        :param id: The id of this UserPrivate.  # noqa: E501
        :type id: str
        :param username: The username of this UserPrivate.  # noqa: E501
        :type username: str
        :param role: The role of this UserPrivate.  # noqa: E501
        :type role: Role
        :param avatar_url: The avatar_url of this UserPrivate.  # noqa: E501
        :type avatar_url: str
        :param bio: The bio of this UserPrivate.  # noqa: E501
        :type bio: str
        """
        self.swagger_types = {
            'email': str,
            'email_verified': bool,
            'id': str,
            'username': str,
            'role': Role,
            'avatar_url': str,
            'bio': str
        }

        self.attribute_map = {
            'email': 'email',
            'email_verified': 'emailVerified',
            'id': 'id',
            'username': 'username',
            'role': 'role',
            'avatar_url': 'avatarUrl',
            'bio': 'bio'
        }
        self._email = email
        self._email_verified = email_verified
        self._id = id
        self._username = username
        self._role = role
        self._avatar_url = avatar_url
        self._bio = bio

    @classmethod
    def from_dict(cls, dikt) -> 'UserPrivate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserPrivate of this UserPrivate.  # noqa: E501
        :rtype: UserPrivate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this UserPrivate.


        :return: The email of this UserPrivate.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserPrivate.


        :param email: The email of this UserPrivate.
        :type email: str
        """

        self._email = email

    @property
    def email_verified(self) -> bool:
        """Gets the email_verified of this UserPrivate.


        :return: The email_verified of this UserPrivate.
        :rtype: bool
        """
        return self._email_verified

    @email_verified.setter
    def email_verified(self, email_verified: bool):
        """Sets the email_verified of this UserPrivate.


        :param email_verified: The email_verified of this UserPrivate.
        :type email_verified: bool
        """

        self._email_verified = email_verified

    @property
    def id(self) -> str:
        """Gets the id of this UserPrivate.


        :return: The id of this UserPrivate.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this UserPrivate.


        :param id: The id of this UserPrivate.
        :type id: str
        """

        self._id = id

    @property
    def username(self) -> str:
        """Gets the username of this UserPrivate.


        :return: The username of this UserPrivate.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserPrivate.


        :param username: The username of this UserPrivate.
        :type username: str
        """

        self._username = username

    @property
    def role(self) -> Role:
        """Gets the role of this UserPrivate.


        :return: The role of this UserPrivate.
        :rtype: Role
        """
        return self._role

    @role.setter
    def role(self, role: Role):
        """Sets the role of this UserPrivate.


        :param role: The role of this UserPrivate.
        :type role: Role
        """

        self._role = role

    @property
    def avatar_url(self) -> str:
        """Gets the avatar_url of this UserPrivate.


        :return: The avatar_url of this UserPrivate.
        :rtype: str
        """
        return self._avatar_url

    @avatar_url.setter
    def avatar_url(self, avatar_url: str):
        """Sets the avatar_url of this UserPrivate.


        :param avatar_url: The avatar_url of this UserPrivate.
        :type avatar_url: str
        """

        self._avatar_url = avatar_url

    @property
    def bio(self) -> str:
        """Gets the bio of this UserPrivate.


        :return: The bio of this UserPrivate.
        :rtype: str
        """
        return self._bio

    @bio.setter
    def bio(self, bio: str):
        """Sets the bio of this UserPrivate.


        :param bio: The bio of this UserPrivate.
        :type bio: str
        """

        self._bio = bio
