# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.role import Role  # noqa: F401,E501
from swagger_server import util


class UserAdminUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, username: str=None, email: str=None, role: Role=None, disabled: bool=None):  # noqa: E501
        """UserAdminUpdate - a model defined in Swagger

        :param username: The username of this UserAdminUpdate.  # noqa: E501
        :type username: str
        :param email: The email of this UserAdminUpdate.  # noqa: E501
        :type email: str
        :param role: The role of this UserAdminUpdate.  # noqa: E501
        :type role: Role
        :param disabled: The disabled of this UserAdminUpdate.  # noqa: E501
        :type disabled: bool
        """
        self.swagger_types = {
            'username': str,
            'email': str,
            'role': Role,
            'disabled': bool
        }

        self.attribute_map = {
            'username': 'username',
            'email': 'email',
            'role': 'role',
            'disabled': 'disabled'
        }
        self._username = username
        self._email = email
        self._role = role
        self._disabled = disabled

    @classmethod
    def from_dict(cls, dikt) -> 'UserAdminUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserAdminUpdate of this UserAdminUpdate.  # noqa: E501
        :rtype: UserAdminUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this UserAdminUpdate.


        :return: The username of this UserAdminUpdate.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserAdminUpdate.


        :param username: The username of this UserAdminUpdate.
        :type username: str
        """

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this UserAdminUpdate.


        :return: The email of this UserAdminUpdate.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserAdminUpdate.


        :param email: The email of this UserAdminUpdate.
        :type email: str
        """

        self._email = email

    @property
    def role(self) -> Role:
        """Gets the role of this UserAdminUpdate.


        :return: The role of this UserAdminUpdate.
        :rtype: Role
        """
        return self._role

    @role.setter
    def role(self, role: Role):
        """Sets the role of this UserAdminUpdate.


        :param role: The role of this UserAdminUpdate.
        :type role: Role
        """

        self._role = role

    @property
    def disabled(self) -> bool:
        """Gets the disabled of this UserAdminUpdate.


        :return: The disabled of this UserAdminUpdate.
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled: bool):
        """Sets the disabled of this UserAdminUpdate.


        :param disabled: The disabled of this UserAdminUpdate.
        :type disabled: bool
        """

        self._disabled = disabled
