# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.role import Role  # noqa: F401,E501
from swagger_server import util


class UserIdRolesBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, roles: List[Role]=None):  # noqa: E501
        """UserIdRolesBody - a model defined in Swagger

        :param roles: The roles of this UserIdRolesBody.  # noqa: E501
        :type roles: List[Role]
        """
        self.swagger_types = {
            'roles': List[Role]
        }

        self.attribute_map = {
            'roles': 'roles'
        }
        self._roles = roles

    @classmethod
    def from_dict(cls, dikt) -> 'UserIdRolesBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The userId_roles_body of this UserIdRolesBody.  # noqa: E501
        :rtype: UserIdRolesBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def roles(self) -> List[Role]:
        """Gets the roles of this UserIdRolesBody.


        :return: The roles of this UserIdRolesBody.
        :rtype: List[Role]
        """
        return self._roles

    @roles.setter
    def roles(self, roles: List[Role]):
        """Sets the roles of this UserIdRolesBody.


        :param roles: The roles of this UserIdRolesBody.
        :type roles: List[Role]
        """
        if roles is None:
            raise ValueError("Invalid value for `roles`, must not be `None`")  # noqa: E501

        self._roles = roles
