# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, username: str=None, avatar_url: str=None, bio: str=None):  # noqa: E501
        """UserUpdate - a model defined in Swagger

        :param username: The username of this UserUpdate.  # noqa: E501
        :type username: str
        :param avatar_url: The avatar_url of this UserUpdate.  # noqa: E501
        :type avatar_url: str
        :param bio: The bio of this UserUpdate.  # noqa: E501
        :type bio: str
        """
        self.swagger_types = {
            'username': str,
            'avatar_url': str,
            'bio': str
        }

        self.attribute_map = {
            'username': 'username',
            'avatar_url': 'avatarUrl',
            'bio': 'bio'
        }
        self._username = username
        self._avatar_url = avatar_url
        self._bio = bio

    @classmethod
    def from_dict(cls, dikt) -> 'UserUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserUpdate of this UserUpdate.  # noqa: E501
        :rtype: UserUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this UserUpdate.


        :return: The username of this UserUpdate.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserUpdate.


        :param username: The username of this UserUpdate.
        :type username: str
        """

        self._username = username

    @property
    def avatar_url(self) -> str:
        """Gets the avatar_url of this UserUpdate.


        :return: The avatar_url of this UserUpdate.
        :rtype: str
        """
        return self._avatar_url

    @avatar_url.setter
    def avatar_url(self, avatar_url: str):
        """Sets the avatar_url of this UserUpdate.


        :param avatar_url: The avatar_url of this UserUpdate.
        :type avatar_url: str
        """

        self._avatar_url = avatar_url

    @property
    def bio(self) -> str:
        """Gets the bio of this UserUpdate.


        :return: The bio of this UserUpdate.
        :rtype: str
        """
        return self._bio

    @bio.setter
    def bio(self, bio: str):
        """Sets the bio of this UserUpdate.


        :param bio: The bio of this UserUpdate.
        :type bio: str
        """

        self._bio = bio
